config/routes.rb
Rails.application.routes.draw do
  devise_for :employers
  devise_for :agencies
  devise_for :users

  resources :welcome

  get 'portal', :to => 'welcome#portal'

  resources :users do
    get 'profile'
  end

  resources :tasks do
    collection do
      post "apply"
    end
  end

  resources :classes do
    collection do
      post "apply"
      post "approve"
      post "deny"
    end
  end

  resources :user_badges

  resources :employers

  resources :agencies

  resources :search do
    collection do
      get "location"
      get "tasks"
    end
  end

  resources :dashboard

  get  '/courses/new',     to: 'classes#new'
  post '/courses',         to: 'classes#create'

  root to: "welcome#index"

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :agency_classes
  has_many :courses, through: :agency_classes
end

app/models/agency_class.rb
class AgencyClass < ActiveRecord::Base
	belongs_to :agency, :foreign_key => "agency_id"
	belongs_to :course, :foreign_key => "course_id"
end

app/models/badge.rb
class Badge < ActiveRecord::Base
	enum skill_type: [ :hard_skill, :soft_skill ]

	has_many :user_badges
  has_many :users, through: :user_badges
	has_one :course

	has_many :badge_tasks
	has_many :tasks, through: :badge_tasks
end

app/models/badge_task.rb
class BadgeTask < ActiveRecord::Base
	belongs_to :badge, :foreign_key => "badge_id"
	belongs_to :task, :foreign_key => "task_id"
end

app/models/course.rb
class Course < ActiveRecord::Base
	# enum skill_type: [ :applied, :accepted, :denied, :completed ]
  enum status: [ :open, :closed ]
	belongs_to :badge
  belongs_to :agency

  has_many :agency_classes
  has_many :agencies, through: :agency_classes

  has_many :user_courses
	has_many :users, through: :user_courses
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :employer_tasks
  has_many :tasks, through: :employer_tasks
end

app/models/employer_task.rb
class EmployerTask < ActiveRecord::Base
	belongs_to :employer, :foreign_key => "employer_id"
	belongs_to :task, :foreign_key => "task_id"
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :user_tasks
	has_many :users, through: :user_tasks

	has_many :badge_tasks
	has_many :badges, through: :badge_tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_badges
  has_many :badges, through: :user_badges

  has_many :user_tasks
  has_many :tasks, through: :user_tasks

  has_many :user_courses
  has_many :courses, through: :user_courses
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
  belongs_to :user, :foreign_key => "user_id"
  belongs_to :badge, :foreign_key => "badge_id"
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	enum status: [ :applied, :accepted, :denied ]
	belongs_to :user, :foreign_key => "user_id"
	belongs_to :course, :foreign_key => "course_id"
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
	include ActiveModel::Validations

	enum task_type: [ :applied, :accepted, :denied ]

	validates :user_id, uniqueness: true
	validates :task_id, uniqueness: true

	belongs_to :user, :foreign_key => "user_id"
	belongs_to :task, :foreign_key => "task_id"

	validate :user_has_met_task_requirements

	def user_has_met_task_requirements
		user_badges = UserBadge.select(:badge_id).where(user_id: self.user_id, badge_id: BadgeTask.select(:badge_id).where(task_id: self.task_id))
		badge_tasks = BadgeTask.select(:badge_id).where(task_id: self.task_id)

		if (user_badges.count != badge_tasks.count)
      errors.add(:user_id, 'User failed to meet requirements of task.')
    end
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_action except: [:index, :apply] do |controller|
		controller.restrict_by_type(Employer.to_s, tasks_path)
	end

	def index
		if (user_signed_in? || agency_signed_in?)
			@tasks = Task.all
		elsif (employer_signed_in?)
			@tasks = current_employer.tasks
		end
	end


  def new
    @employer = current_employer
    @task = Task.new
		respond_to do |format|
			format.html
			format.js
		end
  end

  def create


		begin
    	employer = Employer.find(params[:task][:employer_id])
    rescue ActiveRecord::RecordNotFound => e
      redirect_to tasks_path, :flash => { :error => "Cannot find the employer!" } and return
    end

    @task = Task.new(task_params)

    @task.badges << Badge.find(params[:task_badge][:badge_id].to_i)

    employer.tasks << @task

    if employer.save
      redirect_to tasks_path
    else
      render :new
    end
  end

	def edit
		@task = current_employer.tasks.find(id_params[:id])
	end

	def update
		@task = current_employer.tasks.find(id_params[:id])

		if (@task.update_attributes(task_params))
			redirect_to tasks_path, :notice  => "Successfully updated task."
		else
			redirect_to edit_task_path(@task), :error  => "#{@task.errors.full_messages.join(', ')}"
		end
	end

	def destroy
		@task = current_employer.tasks.find(id_params[:id])
		respond_to do |format|
			current_employer.tasks.delete(@task)
			format.js
		end
	end

	def apply
		task = Task.find(id_params[:id])

		current_user.tasks << task
		respond_to do |format|
			format.js
		end
	end

  protected

  # security issue, Rails has adopted a standard called "strong parameters" for mass assignment.
  def task_params
    params.require(:task).permit(:title, :description, :address, :start_date, :end_date, :duration)
  end

	def id_params
		params.permit(:id)
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @userbadge = UserBadge.new
    @badges = Badge.all
  end

  def show
    @badges = current_user.badges
    @earned_count = @badges.count
    @tasks_applied_count = current_user.user_tasks.where(task_type: 0).count
    @tasks_accepted_count = current_user.user_tasks.where(task_type: 1).count
    @courses_applied_count = current_user.user_courses.where(status: 0).count
    @courses_accepted_count = current_user.user_courses.where(status: 1).count
    @courses_completed_count = current_user.user_courses.where(status: 2).count

  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tasks/destroy.js.erb
window.location.reload();

app/views/tasks/edit.html.erb
<h2>Edit Your Task</h2>
<%= bootstrap_form_for(@task) do |f| %>
  <div>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.text_field "description" %>
  </div>
  <div>
    <%= f.text_field "address", class: "address-lookup" %>
  </div>
  <div>
    <%= f.text_field "start_date", data: {provide: "datepicker"}, value: "" %>
  </div>
  <div>
    <%= f.text_field "end_date", data: {provide: "datepicker"}, value: "" %>
  </div>
  <div>
    <%= f.text_field "duration" %>
  </div>
  <div>
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<div class="row">
	<h2>Available Tasks</h2>

	<div id="map"></div>
	<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDcUSl61EYZETz7KfWIv3dw9NUMj-Tue78&libraries=places&callback=initMap" async defer></script>
</div>
<div class="row tasks">
	<div class="col-xs-12 col-sm-10 col-sm-offset-1">
		<% @tasks.each do |task| %>
			<% user_task = current_user.user_tasks.find_by(user_id: current_user.id, task_id: task.id) if user_signed_in? %>
			<% meets_req = UserTask.new(user_id: current_user.id, task_id: task.id).valid? if user_signed_in?  %>

				<div class="col-md-12 row">
					<div class="col-md-8 row">
						<div class="col-md-12">
							<h3>
								<%= task.title %>
								<% if (employer_signed_in?) %>
									&nbsp;<%= link_to "<i class=\"fa fa-wrench\"></i>".html_safe, edit_task_path(task) %>&nbsp;<%= link_to "<i class=\"fa fa-trash-o\"></i>".html_safe, task_path(task), method: :delete, remote: true %>
								<% end %>
							</h3>
						</div>
						<div class="col-md-12">
							<h4>Address - <%= task.address %></h4>
						</div>
						<div class="col-md-12">
							<h5>Duration: <%= task.duration %></h5>
						</div>
						<div class="col-md-12">
							<% if user_signed_in? %><h5>Status: <%= user_task.nil? ? "Not Applied" : user_task.task_type.to_s.humanize %></h5><% end %>
						</div>
						<div class="col-md-12">
							<p><%= task.description %></p>
						</div>
						<div class="col-md-12">
							<a href="/" class="showBadge" onclick="return false"/>View the list of required badges</a>
						</div>
						<div class="col-md-12">
							<ul>
									<% task.badges.each do |badge| %>
									<li>
										<div class="badges-required">
											<%= image_tag(badge.image, size: "150", alt: "Badges") %>
											<p><%= badge.name %></p>
										</div>
									</li>
									<% end %>
							</ul>
						</div>
					</div>
					<div class="col-md-4">
						<% if (user_signed_in? && user_task.nil? && meets_req) %>
							<%= link_to("Apply", { :action => "apply", :id => task.id }, class: "apply", method: :post, remote: true) %>
						<% elsif (user_signed_in? && user_task.nil? && !meets_req) %>
							<a href="javascript:" class="denied">Missing Required Badge</a>
						<% end %>
					</div>
					<div class="col-xs-12">
						<hr class="clearfix" />
					</div>
				</div>
		<% end %>
<% if (employer_signed_in?) %>
<%= link_to '<i class="fa fa-plus"></i> Add Task'.html_safe, new_task_path, class: "btn btn-primary" %>
<% end %>


<script>
	$(".showBadge").click(function(){
    $(this).parent().parent().find((".badges-required")).last().toggle()
	});
</script>


	</div>
</div>

app/views/tasks/new.html.erb
<h2>Create a Task</h2>
<%= bootstrap_form_for(@task) do |f| %>
  <%= f.hidden_field :employer_id, :value => @employer.id %>

  <div>
    <%= f.text_field "title" %>
  </div>
  <div>
    <%= f.text_field "description" %>
  </div>
  <div>
    <%= f.text_field "address", class: "address-lookup" %>
  </div>
  <div>
    <%= f.text_field "start_date", data: {provide: "datepicker"}, value: "" %>
  </div>
  <div>
    <%= f.text_field "end_date", data: {provide: "datepicker"}, value: "" %>
  </div>
  <div>
    <%= f.text_field "duration" %>
  </div>
  <div>
    <%= select("task_badge", "badge_id", Badge.all.collect {|p| [ p.name, p.id ] } ) %>
  </div>
  <div>
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>

app/views/users/_nav.html.erb
<div class="col-md-3 profile">
  <%= image_tag("profile.jpg", size: "150", alt: "Badges") %>
  <h2>Profile Name</h2>
  <h5>Member since 2015</h5>
  <h3><span class="glyphicon glyphicon-cog" aria-hidden="true"></span> Settings</h3>
  <ul>
    <li><%= link_to "Dashboard", "/users/#{current_user.id}" %></li>
    <li><%= link_to "Profile", "/users/#{current_user.id}/profile" %></li>
    <!-- <li><%= link_to "Account Setting", "/users/#{current_user.id}/profile" %></li> -->
  </ul>
</div>

app/views/users/index.html.erb
<!-- The href of the button to launch the modal must match the id of the modal dialog. -->
<hr>
<% @users.each do |user| %>
  <div class="forte-users-badge-assign">

      <%= form_for @userbadge  do |f| %>

          <%= f.hidden_field :user_id, :value => user.id %>
          <%= user.email %>
          <% user.badges.each do |badge| %>
             , <%= badge.name %>
          <% end %>

          <%= select("user_badge", "badge_id", Badge.all.collect {|p| [ p.name, p.id ] } ) %>

         <%= f.submit "Save" ,class: "btn btn-primary save" %>

      <% end %>
  </div>
<% end %>

app/views/users/profile.html.erb
<%= render partial: "nav" %>
<div class="col-md-9">
  <h2>My Profile</h2>
	Email: <%= current_user.email%><br />
</div>

app/views/users/show.html.erb
<%= render partial: "nav" %>
<div class="col-md-9">
  <h2>Achievements</h2>
  <div class="row achievement">
      <div class="col-md-2"><div class="circle-1"><%= @earned_count %></div><p>Badges Earned</p></div>
      <div class="col-md-2"><div class="circle-1"><%= @tasks_applied_count %></div><p>Tasks Applied</p></div>
      <div class="col-md-2"><div class="circle-1"><%= @tasks_accepted_count %></div><p>Tasks Accepted</p></div>
      <div class="col-md-2"><div class="circle-1"><%= @courses_applied_count %></div><p>Courses Applied</p></div>
      <div class="col-md-2"><div class="circle-1"><%= @courses_accepted_count %></div><p>Courses Accepted</p></div>
      <div class="col-md-2"><div class="circle-1"><%= @courses_completed_count %></div><p>Courses Completed</p></div>
  </div>
  <h2>Badges</h2>
  <div class="row">
      <% @badges.each do |badge| %>
        <div class="col-md-4 col-lg-3">
          <div class="badge-box">
            <%= image_tag(badge.image, size: "150", alt: "Badges") %>
            <h3><%= badge.name %></h3>
          </div>
        </div>
      <% end %>
  </div>
</div>