config/routes.rb
Rails.application.routes.draw do
  devise_for :employers
  devise_for :agencies
  devise_for :users

  resources :welcome

  get 'portal', :to => 'welcome#portal'

  resources :users do
    get 'profile'
  end

  resources :tasks do
    collection do
      post "apply"
    end
  end

  resources :classes do
    collection do
      post "apply"
      post "approve"
      post "deny"
    end
  end

  resources :user_badges

  resources :employers

  resources :agencies

  resources :search do
    collection do
      get "location"
      get "tasks"
    end
  end

  resources :dashboard

  get  '/courses/new',     to: 'classes#new'
  post '/courses',         to: 'classes#create'

  root to: "welcome#index"

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :agency_classes
  has_many :courses, through: :agency_classes
end

app/models/agency_class.rb
class AgencyClass < ActiveRecord::Base
	belongs_to :agency, :foreign_key => "agency_id"
	belongs_to :course, :foreign_key => "course_id"
end

app/models/badge.rb
class Badge < ActiveRecord::Base
	enum skill_type: [ :hard_skill, :soft_skill ]

	has_many :user_badges
  has_many :users, through: :user_badges
	has_one :course

	has_many :badge_tasks
	has_many :tasks, through: :badge_tasks
end

app/models/badge_task.rb
class BadgeTask < ActiveRecord::Base
	belongs_to :badge, :foreign_key => "badge_id"
	belongs_to :task, :foreign_key => "task_id"
end

app/models/course.rb
class Course < ActiveRecord::Base
	# enum skill_type: [ :applied, :accepted, :denied, :completed ]
  enum status: [ :open, :closed ]
	belongs_to :badge
  belongs_to :agency

  has_many :agency_classes
  has_many :agencies, through: :agency_classes

  has_many :user_courses
	has_many :users, through: :user_courses
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :employer_tasks
  has_many :tasks, through: :employer_tasks
end

app/models/employer_task.rb
class EmployerTask < ActiveRecord::Base
	belongs_to :employer, :foreign_key => "employer_id"
	belongs_to :task, :foreign_key => "task_id"
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :user_tasks
	has_many :users, through: :user_tasks

	has_many :badge_tasks
	has_many :badges, through: :badge_tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_badges
  has_many :badges, through: :user_badges

  has_many :user_tasks
  has_many :tasks, through: :user_tasks

  has_many :user_courses
  has_many :courses, through: :user_courses
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
  belongs_to :user, :foreign_key => "user_id"
  belongs_to :badge, :foreign_key => "badge_id"
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	enum status: [ :applied, :accepted, :denied ]
	belongs_to :user, :foreign_key => "user_id"
	belongs_to :course, :foreign_key => "course_id"
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
	include ActiveModel::Validations

	enum task_type: [ :applied, :accepted, :denied ]

	validates :user_id, uniqueness: true
	validates :task_id, uniqueness: true

	belongs_to :user, :foreign_key => "user_id"
	belongs_to :task, :foreign_key => "task_id"

	validate :user_has_met_task_requirements

	def user_has_met_task_requirements
		user_badges = UserBadge.select(:badge_id).where(user_id: self.user_id, badge_id: BadgeTask.select(:badge_id).where(task_id: self.task_id))
		badge_tasks = BadgeTask.select(:badge_id).where(task_id: self.task_id)

		if (user_badges.count != badge_tasks.count)
      errors.add(:user_id, 'User failed to meet requirements of task.')
    end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout "homepage"
  skip_before_action :authenicate_override

  def index
  end

  def portal
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<div class="row home">
    <div class="col-xs-10 col-xs-offset-1">
      <%= image_tag("logo2.png", height: "200", alt: "Logo") %>
      <h1>Pulling Skills to Work for Impact-Driven Companies</h1>
      <%= link_to 'Log in as an User', new_user_session_path, :class => "signin" %>
      <div class="row">
        <div class="col-xs-12">
          <div class="col-xs-6 text-right"><%= link_to "I am an Agency", new_agency_session_path, class: "btn btn-signin btn-md" %></div>
          <div class="col-xs-6 text-left"><%= link_to "I am an Employer", new_employer_session_path, class: "btn btn-signin btn-md" %></div>
        </div>
      </div>
      <small>New to Knack ? Learn more about it</small>
    </div>
</div>

app/views/welcome/portal.html.erb
<div class="row portal">
  <p class="well">Welcome! This page is an exclusive login for Agencies and Employers. Please select an appropriate login below.</p>
  <div class="col-xs-10 col-xs-offset-1">
    <div class="col-md-12">

      <div class="col-md-6 text-right"><%= link_to "I am an Agency", new_agency_session_path, class: "btn btn-success btn-lg" %></div>
      <div class="col-md-6 text-left"><%= link_to "I am an Employer", new_employer_session_path, class: "btn btn-success btn-lg" %></div>

    </div>
  </div>
</div>