config/routes.rb
Rails.application.routes.draw do
  devise_for :employers
  devise_for :agencies
  devise_for :users

  resources :welcome

  get 'portal', :to => 'welcome#portal'

  resources :users do
    get 'profile'
  end

  resources :tasks do
    collection do
      post "apply"
    end
  end

  resources :classes do
    collection do
      post "apply"
      post "approve"
      post "deny"
    end
  end

  resources :user_badges

  resources :employers

  resources :agencies

  resources :search do
    collection do
      get "location"
      get "tasks"
    end
  end

  resources :dashboard

  get  '/courses/new',     to: 'classes#new'
  post '/courses',         to: 'classes#create'

  root to: "welcome#index"

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :agency_classes
  has_many :courses, through: :agency_classes
end

app/models/agency_class.rb
class AgencyClass < ActiveRecord::Base
	belongs_to :agency, :foreign_key => "agency_id"
	belongs_to :course, :foreign_key => "course_id"
end

app/models/badge.rb
class Badge < ActiveRecord::Base
	enum skill_type: [ :hard_skill, :soft_skill ]

	has_many :user_badges
  has_many :users, through: :user_badges
	has_one :course

	has_many :badge_tasks
	has_many :tasks, through: :badge_tasks
end

app/models/badge_task.rb
class BadgeTask < ActiveRecord::Base
	belongs_to :badge, :foreign_key => "badge_id"
	belongs_to :task, :foreign_key => "task_id"
end

app/models/course.rb
class Course < ActiveRecord::Base
	# enum skill_type: [ :applied, :accepted, :denied, :completed ]
  enum status: [ :open, :closed ]
	belongs_to :badge
  belongs_to :agency

  has_many :agency_classes
  has_many :agencies, through: :agency_classes

  has_many :user_courses
	has_many :users, through: :user_courses
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :employer_tasks
  has_many :tasks, through: :employer_tasks
end

app/models/employer_task.rb
class EmployerTask < ActiveRecord::Base
	belongs_to :employer, :foreign_key => "employer_id"
	belongs_to :task, :foreign_key => "task_id"
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :user_tasks
	has_many :users, through: :user_tasks

	has_many :badge_tasks
	has_many :badges, through: :badge_tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_badges
  has_many :badges, through: :user_badges

  has_many :user_tasks
  has_many :tasks, through: :user_tasks

  has_many :user_courses
  has_many :courses, through: :user_courses
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
  belongs_to :user, :foreign_key => "user_id"
  belongs_to :badge, :foreign_key => "badge_id"
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	enum status: [ :applied, :accepted, :denied ]
	belongs_to :user, :foreign_key => "user_id"
	belongs_to :course, :foreign_key => "course_id"
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
	include ActiveModel::Validations

	enum task_type: [ :applied, :accepted, :denied ]

	validates :user_id, uniqueness: true
	validates :task_id, uniqueness: true

	belongs_to :user, :foreign_key => "user_id"
	belongs_to :task, :foreign_key => "task_id"

	validate :user_has_met_task_requirements

	def user_has_met_task_requirements
		user_badges = UserBadge.select(:badge_id).where(user_id: self.user_id, badge_id: BadgeTask.select(:badge_id).where(task_id: self.task_id))
		badge_tasks = BadgeTask.select(:badge_id).where(task_id: self.task_id)

		if (user_badges.count != badge_tasks.count)
      errors.add(:user_id, 'User failed to meet requirements of task.')
    end
	end
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
  before_action except: [:index, :apply, :approve, :deny] do |controller|
    controller.restrict_by_type(Agency.to_s, classes_path)
  end

	def index
		@classes = Course.all
	end

  def new
    @class = Course.new
    @agency = current_agency
    respond_to do |format|
      format.html
      format.js
    end
  end


  def create
    # byebug

    begin
      agency = Agency.find(params[:course][:agency_id])
    rescue ActiveRecord::RecordNotFound => e
      redirect_to classes_path, :flash => { :error => "Cannot find the agency!" } and return
    end

    @class = Course.new(class_params)

    agency.courses << @class

    if agency.save
      redirect_to classes_path
    else
      render :new
    end
  end

  def apply
		course = Course.find(id_params[:id])

		current_user.courses << course
		respond_to do |format|
			format.js
		end
	end

  def approve
    user_course = UserCourse.find_by(user_id: request_params[:user_id], course_id: request_params[:course_id])
    user_course.status = 1
    user_course.save!
    respond_to do |format|
			format.js
		end
  end

  def deny
    user_course = UserCourse.find_by(user_id: request_params[:user_id], course_id: request_params[:course_id])
    user_course.status = 2
    user_course.save!
    respond_to do |format|
			format.js
		end
  end

  protected

  # security issue, Rails has adopted a standard called "strong parameters" for mass assignment.
  def class_params
    params.require(:course).permit(:name, :description, :status, :capacity, :start_date, :end_date)
  end

  def id_params
    params.permit(:id)
  end

  def request_params
    params.permit(:user_id, :course_id)
  end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/classes/apply.js.erb
window.location.reload();

app/views/classes/approve.js.erb
window.location.reload();

app/views/classes/deny.js.erb
window.location.reload();

app/views/classes/index.html.erb
<div class="row courses">
		<h2>Available Classes</h2>
	<div class="col-xs-12">
		<div class="row">
			<div class="col-md-4">
				<h4>Name & Description of the course</h4>
			</div>
			<div class="col-md-2">
				<h4>Status</h4>
			</div>
			<div class="col-md-2">
				<h4>Start Date</h4>
			</div>
			<div class="col-md-2">
				<h4>End Date</h4>
			</div>
			<div class="col-md-2">
			</div>
		</div>
	<% @classes.each do |course| %>
		<% user_course = current_user.user_courses.find_by(user_id: current_user.id, course_id: course.id) if user_signed_in? %>
		<div class="row course">
			<div class="col-md-4">
						<h3><%= course.name %></h3>
						<h5><%= course.description %></h5>
						<p>Max Capacity: <strong><%= course.capacity %></strong></p>
			</div>
			<div class="col-md-2">
					<p><%= course.status %></p>
			</div>
			<div class="col-md-2">
					<p><strong><%= course.start_date %></strong></p>
			</div>
			<div class="col-md-2">
				<p><strong><%= course.end_date %></strong></p>
			</div>
			<div class="col-md-2">
				<% if (user_signed_in? && user_course.nil?) %>
					<%= link_to("Apply", { :action => "apply", :id => course.id }, class: "apply", method: :post, remote: true) %>
				<% elsif (user_signed_in? && !user_course.nil?) %>
					Applied
				<% end %>
			</div>

		</div>

  <% end %>

<% if (agency_signed_in?) %>
<%= link_to '<i class="fa fa-plus"></i> Add Class'.html_safe, new_class_path, class: "btn btn-primary" %>
<% end %>

	</div>
</div>

app/views/classes/new.html.erb
<h2>Create a class</h2>
<%= bootstrap_form_for(@class) do |f| %>
  <%= f.hidden_field :agency_id, :value => @agency.id %>

  <div>
    <%= f.text_field "name" %>
  </div>
  <div>
    <%= f.text_field "description" %>
  </div>
  <div>
    <%= f.text_field "status" %>
  </div>
  <div>
    <%= f.text_field "capacity" %>
  </div>
  <div>
    <%= f.text_field "start_date", data: {provide: "datepicker"}, value: "" %>
  </div>
  <div>
    <%= f.text_field "end_date", data: {provide: "datepicker"}, value: "" %>
  </div>
  <div>
    <%= f.submit "Save", class: "btn btn-success" %>
  </div>
<% end %>