config/routes.rb
Rails.application.routes.draw do
  devise_for :employers
  devise_for :agencies
  devise_for :users

  resources :welcome

  get 'portal', :to => 'welcome#portal'

  resources :users do
    get 'profile'
  end

  resources :tasks do
    collection do
      post "apply"
    end
  end

  resources :classes do
    collection do
      post "apply"
      post "approve"
      post "deny"
    end
  end

  resources :user_badges

  resources :employers

  resources :agencies

  resources :search do
    collection do
      get "location"
      get "tasks"
    end
  end

  resources :dashboard

  get  '/courses/new',     to: 'classes#new'
  post '/courses',         to: 'classes#create'

  root to: "welcome#index"

end

app/models/agency.rb
class Agency < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :agency_classes
  has_many :courses, through: :agency_classes
end

app/models/agency_class.rb
class AgencyClass < ActiveRecord::Base
	belongs_to :agency, :foreign_key => "agency_id"
	belongs_to :course, :foreign_key => "course_id"
end

app/models/badge.rb
class Badge < ActiveRecord::Base
	enum skill_type: [ :hard_skill, :soft_skill ]

	has_many :user_badges
  has_many :users, through: :user_badges
	has_one :course

	has_many :badge_tasks
	has_many :tasks, through: :badge_tasks
end

app/models/badge_task.rb
class BadgeTask < ActiveRecord::Base
	belongs_to :badge, :foreign_key => "badge_id"
	belongs_to :task, :foreign_key => "task_id"
end

app/models/course.rb
class Course < ActiveRecord::Base
	# enum skill_type: [ :applied, :accepted, :denied, :completed ]
  enum status: [ :open, :closed ]
	belongs_to :badge
  belongs_to :agency

  has_many :agency_classes
  has_many :agencies, through: :agency_classes

  has_many :user_courses
	has_many :users, through: :user_courses
end

app/models/employer.rb
class Employer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :employer_tasks
  has_many :tasks, through: :employer_tasks
end

app/models/employer_task.rb
class EmployerTask < ActiveRecord::Base
	belongs_to :employer, :foreign_key => "employer_id"
	belongs_to :task, :foreign_key => "task_id"
end

app/models/task.rb
class Task < ActiveRecord::Base
	has_many :user_tasks
	has_many :users, through: :user_tasks

	has_many :badge_tasks
	has_many :badges, through: :badge_tasks
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_badges
  has_many :badges, through: :user_badges

  has_many :user_tasks
  has_many :tasks, through: :user_tasks

  has_many :user_courses
  has_many :courses, through: :user_courses
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
  belongs_to :user, :foreign_key => "user_id"
  belongs_to :badge, :foreign_key => "badge_id"
end

app/models/user_course.rb
class UserCourse < ActiveRecord::Base
	enum status: [ :applied, :accepted, :denied ]
	belongs_to :user, :foreign_key => "user_id"
	belongs_to :course, :foreign_key => "course_id"
end

app/models/user_task.rb
class UserTask < ActiveRecord::Base
	include ActiveModel::Validations

	enum task_type: [ :applied, :accepted, :denied ]

	validates :user_id, uniqueness: true
	validates :task_id, uniqueness: true

	belongs_to :user, :foreign_key => "user_id"
	belongs_to :task, :foreign_key => "task_id"

	validate :user_has_met_task_requirements

	def user_has_met_task_requirements
		user_badges = UserBadge.select(:badge_id).where(user_id: self.user_id, badge_id: BadgeTask.select(:badge_id).where(task_id: self.task_id))
		badge_tasks = BadgeTask.select(:badge_id).where(task_id: self.task_id)

		if (user_badges.count != badge_tasks.count)
      errors.add(:user_id, 'User failed to meet requirements of task.')
    end
	end
end

app/helpers/agencies_helper.rb
module AgenciesHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Knack" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "homepage" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body data-controller="<%= controller_name %>" data-action="<%= action_name %>">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("knack_icon.png", height: "45", alt: "Brand"), "dashboard", class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li><%= link_to 'Tasks', tasks_path %></li>
                <li><%= link_to 'Classes', classes_path %></li>
                <li><p class="navbar-text"><span>Hello <%= link_to current_user.email, "/users/#{current_user.id}" %></span> <span>(<%= link_to "not you?", destroy_user_session_path, :method => :delete %>)</span> !</p></li>
              <% elsif employer_signed_in? %>
                <li><%= link_to 'Tasks', tasks_path %></li>
                <li><%= link_to 'Classes', classes_path %></li>
                <li><p class="navbar-text"><span>Hello <%= link_to current_employer.email, "/employers/#{current_employer.id}" %></span> <span>(<%= link_to "not you?", destroy_employer_session_path, :method => :delete %>)</span> !</p></li>
              <% elsif agency_signed_in? %>
                <li><%= link_to 'Tasks', tasks_path %></li>
                <li><%= link_to 'Classes', classes_path %></li>
                <li><%= link_to 'Assign Badges', users_path %></li>

                <li><p class="navbar-text"><span>Hello <%= link_to current_agency.email, "/agencies/#{current_agency.id}" %></span> <span>(<%= link_to "not you?", destroy_agency_session_path, :method => :delete %>)</span> !</p></li>

              <% else %>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>
  <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Knack 2016</p>
      </footer>

    </div> <!-- /container -->
  </body>

</html>

app/views/layouts/homepage.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Knack" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "homepage" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body data-controller="<%= controller_name %>" data-action="<%= action_name %>">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("knack_icon.png", height: "45", alt: "Brand"), "dashboard", class: "navbar-brand" %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
              <% if user_signed_in? %>
                <li><%= link_to 'Tasks', tasks_path %></li>
                <li><%= link_to 'Classes', classes_path %></li>
                <li><p class="navbar-text"><span>Hello <%= link_to current_user.email, "/users/#{current_user.id}" %></span> <span>(<%= link_to "not you?", destroy_user_session_path, :method => :delete %>)</span> !</p></li>
              <% elsif employer_signed_in? %>
                <li><%= link_to 'Tasks', tasks_path %></li>
                <li><%= link_to 'Classes', classes_path %></li>
                <li><p class="navbar-text"><span>Hello <%= link_to current_employer.email, "/employers/#{current_employer.id}" %></span> <span>(<%= link_to "not you?", destroy_employer_session_path, :method => :delete %>)</span> !</p></li>
              <% elsif agency_signed_in? %>
                <li><%= link_to 'Tasks', tasks_path %></li>
                <li><%= link_to 'Classes', classes_path %></li>
                <li><p class="navbar-text"><span>Hello <%= link_to current_agency.email, "/agencies/#{current_agency.id}" %></span> <span>(<%= link_to "not you?", destroy_agency_session_path, :method => :delete %>)</span> !</p></li>
              <% else %>
                <li><%= link_to 'Sign in', new_user_session_path %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>
<div id="content">
  <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Knack 2016</p>
      </footer>

    </div> <!-- /container -->
</div><!-- /content -->
  </body>

</html>